import { readFile, writeFile, mkdir, rm, copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.join(root,'dist-preview');
await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});
const fixture=JSON.parse(await readFile(path.join(root,'preview/demo-data.json'),'utf8'));
if(fixture.mode!=='synthetic-visual-preview'||fixture.patients.some(p=>p.synthetic!==1))throw Error('Refusing non-synthetic preview data');
let html=await readFile(path.join(root,'frontend/index.html'),'utf8');
html=html.replace('<title>InBodyStage1 · Coherence</title>','<title>InBodyStage1 · Visual Preview</title>').replace('<script src="/app.js" defer></script>', '<script src="/demo-data.js" defer></script><script src="/demo-adapter.js" defer></script><script src="/app.js" defer></script>');
const extra='\n.preview-banner{background:#e4efff;color:#275da1;border:1px solid #bfd5f0;padding:11px 16px;border-radius:5px;font-size:11px;margin-bottom:25px;}\n';
const css=(await readFile(path.join(root,'frontend/style.css'),'utf8'))+extra;
const fixtureJS='window.INBODY_PREVIEW_DATA='+JSON.stringify(fixture).replaceAll('<','\\u003c')+';\n';
const adapter=await readFile(path.join(root,'preview/demo-adapter.js'),'utf8');
const app=await readFile(path.join(root,'frontend/app.js'),'utf8');
await writeFile(path.join(out,'index.html'),html);
await writeFile(path.join(out,'style.css'),css);
await writeFile(path.join(out,'demo-data.js'),fixtureJS);
await writeFile(path.join(out,'demo-adapter.js'),adapter);
await writeFile(path.join(out,'app.js'),app);
const standalone=html.replace('<link rel="stylesheet" href="/style.css">','<style>'+css+'</style>').replace(/<script src="[^\"]+" defer><\/script>/g,'').replace('</body>','<script>'+fixtureJS+adapter+app+'</script></body>');
await writeFile(path.join(path.dirname(root),'InBodyStage1_Visual_Preview.html'),standalone);
console.log('Built static synthetic preview: dist-preview (5 files). Local standalone preview also generated.');
